name: ReleaseNewVersion

on: [push]

jobs:
  readPomAndLastRelease:
    runs-on: ubuntu-latest
    outputs:
      rawPomVersion: ${{steps.getXml.outputs.info}}
      pomVersion: 'v${{steps.getXml.outputs.info}}'
      lastReleaseId: ${{steps.lastRelease.outputs.release}}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get XML Info
      id: getXml
      uses: mavrosxristoforos/get-xml-info@1.1.1
      with:
        xml-file: 'pom.xml'
        xpath: "//*[local-name()='project']/*[local-name()='version']"
    - id: lastRelease
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: Christian-2003/VATE
    
  build:
    needs: readPomAndLastRelease
    if: needs.readPomAndLastRelease.outputs.pomVersion != needs.readPomAndLastRelease.outputs.lastReleaseId
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
    - run: echo 'VATE Version ${{needs.readPomAndLastRelease.outputs.pomVersion}} and ${{needs.readPomAndLastRelease.outputs.lastReleaseId}}'
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Convert .jar to .exe
      run: |
        wget https://deac-riga.dl.sourceforge.net/project/launch4j/launch4j-3/3.50/launch4j-3.50-linux-x64.tgz
        tar xzf launch4j-3.50-linux-x64.tgz
        cp target/VATE-${{ needs.readPomAndLastRelease.outputs.rawPomVersion }}.jar target/VATE.jar
        cd launch4j
        ./launch4j.jar /home/runner/work/VATE/VATE/launch4j-config.xml
    - uses: ncipollo/release-action@v1
      with:
        name: 'VATE Version ${{ needs.readPomAndLastRelease.outputs.rawPomVersion }}'
        tag: ${{needs.readPomAndLastRelease.outputs.pomVersion}}
        artifacts: "target/VATE-${{ needs.readPomAndLastRelease.outputs.rawPomVersion }}.jar,target/VATE.exe"
        body: 'Release VATE Version ${{ needs.readPomAndLastRelease.outputs.rawPomVersion }}'
